Repository AICoE/seraph, pull requests merged in 2021-11, with the labels that each got.

#10 Update README.md
  README.md
Labels: documentation, good first issue, size/S, lgtm, approved

#11 chore: Set owners to tumido and thor
  OWNERS
Labels: size/S, lgtm, approved

#13 feat: Init cluster scope resources
  cluster-scope/base/core/namespaces/ingress/kustomization.yaml
  cluster-scope/base/core/namespaces/ingress/namespace.yaml
  cluster-scope/base/core/namespaces/platform-mq/kustomization.yaml
  cluster-scope/base/core/namespaces/platform-mq/namespace.yaml
  cluster-scope/overlays/dev/kustomization.yaml
  cluster-scope/overlays/operate-first/README.md
Labels: size/S, lgtm, approved

#12 feat: Init Kafka deployment
  platform-mq/base/kafka.yaml
  platform-mq/base/kt_platform.payload-status.yaml
  platform-mq/base/kt_platform.upload.advisor.yaml
  platform-mq/base/kt_platform.upload.announce.yaml
  platform-mq/base/kt_platform.upload.available.yaml
  platform-mq/base/kt_platform.upload.host-ingress.yaml
  platform-mq/base/kustomization.yaml
  platform-mq/overlays/dev/kustomization.yaml
  platform-mq/overlays/operate-first/kustomization.yaml
Labels: lgtm, approved, size/M
